version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
        environment:
          POSEIDON_CONFIG: /tmp/poseidonWork/config/poseidon.config
    services:
      - rabbitmq-server
    working_directory: /tmp/poseidonWork
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python deps in venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: 
          name: run tests
          command: |
            . venv/bin/activate
            py.test -v --cov=/tmp/poseidonWork/poseidon --cov-report term-missing
            bash <(curl -s https://codecov.io/bash) -t 992b90e5-a0b2-45c5-b9d5-3baddc184162
